name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20.x", "1.21.x"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: true
    - name: Download dependencies
      run: go mod download
    - name: Test
      run: make cover
    - name: Upload coverage
      uses: codecov/codecov-action@v3
